// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repo

import (
	"context"
)

type Querier interface {
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	GetUser(ctx context.Context, id uint32) (User, error)
}

var _ Querier = (*Queries)(nil)
