// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repo

import (
	"time"
)

type User struct {
	ID        uint32    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Bio       string    `json:"bio"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
