local:
  server:
    port: 8080
  services:
    user: localhost:3636
  logger:
    level: debug
    pretty: true
kube:
  server:
    port: 8080
  services:
    user: userservice:3636
  logger:
    level: info
    pretty: false
